In [2]:
import numpy as np

In [3]:
mylist = [1, 2, 3]

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.random.seed(101)
arr = np.random.randint(0, 100, 10)

In [8]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [9]:
arr2 = np.random.randint(0, 100, 10)

In [10]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [11]:
arr.max()

95